; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
PrivilegesRequired=admin
AppId={{C206A02A-CD20-4AC2-9A17-B5D2653881F2}
AppName=BFME2 PatchSwitcher Setup
AppVersion=1.0
;AppVerName=BFME2 PatchSwitcher 1.0
AppPublisher=Paramartha Saha
AppPublisherURL=http://forshire.blogspot.com
AppSupportURL=http://forshire.blogspot.com
AppUpdatesURL=http://forshire.blogspot.com
DefaultDirName={pf}\BFME2 PatchSwitcher
DisableProgramGroupPage=yes
OutputDir=C:\Users\Paramartha Saha\Desktop\Output
OutputBaseFilename=BFME2 PatchSwitcher Setup
SetupIconFile=C:\Users\Paramartha Saha\Desktop\All Folder\old proj\PatchSwitcher_BFME222 - Copy\PatchSwitcher_BFME2\PatchSwitcher_BFME2\ico.ico
SolidCompression=yes
Compression=lzma2/ultra64
LZMAUseSeparateProcess=yes
LZMANumFastBytes=273

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
[code]

function dirPath(Param: string): string;
var path : String ;
Begin
if RegQueryStringValue(HKEY_LOCAL_MACHINE, 'SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\lotrbfme2.exe',
     'Path', path) then
      begin
     
    Result := ExtractFileDir(path+'\');
    begin
end;
    end 
end; 


[Files]
Source: "C:\Users\Paramartha Saha\Desktop\All Folder\old proj\PatchSwitcher_BFME222 - Copy\PatchSwitcher_BFME2\PatchSwitcher_BFME2\bin\Release\BFME2 PatchSwitcher.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Paramartha Saha\Desktop\All Folder\old proj\PatchSwitcher_BFME222 - Copy\PatchSwitcher_BFME2\PatchSwitcher_BFME2\bin\Release\100\*"; DestDir: "{app}\100"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Paramartha Saha\Desktop\All Folder\old proj\PatchSwitcher_BFME222 - Copy\PatchSwitcher_BFME2\PatchSwitcher_BFME2\bin\Release\106\*"; DestDir: "{app}\106"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Paramartha Saha\Desktop\All Folder\old proj\PatchSwitcher_BFME222 - Copy\PatchSwitcher_BFME2\PatchSwitcher_BFME2\bin\Release\109\*"; DestDir: "{app}\109"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Paramartha Saha\Desktop\All Folder\old proj\PatchSwitcher_BFME222 - Copy\PatchSwitcher_BFME2\PatchSwitcher_BFME2\bin\Release\200\*"; DestDir: {code:dirPath}; Flags: ignoreversion recursesubdirs createallsubdirs

; NOTE: Don't use "Flags: ignoreversion" on any shared system files
[Dirs]
Name: "{code:dirPath}\Patch 1.09 Changelogs and Credits"
[InstallDelete]
Type: files; Name: "{code:dirPath}\__BT2DC-v1.09w.big"
Type: files; Name: "{code:dirPath}\__109floors.big"
[UninstallDelete]
Type: files; Name: "{code:dirPath}\__BT2DC-v1.09w.big"
Type: files; Name: "{code:dirPath}\__109floors.big"

[Icons]
Name: "{commonprograms}\BFME2 PatchSwitcher"; Filename: "{app}\BFME2 PatchSwitcher.exe"
Name: "{commondesktop}\BFME2 PatchSwitcher"; Filename: "{app}\BFME2 PatchSwitcher.exe"

[Run]
Filename: "{app}\BFME2 PatchSwitcher.exe"; Description: "{cm:LaunchProgram,BFME2 PatchSwitcher}"; Flags:runascurrentuser nowait postinstall skipifsilent

